name             'martinb3-minecraft'
maintainer       'Martin Smith'
maintainer_email 'martin@mbs3.org'
license          'Apache 2'
description      'Installs/Configures minecraft'
long_description 'Installs/Configures default for a minecraft cloud server'
version          '0.1.0'

depends 'martinb3-base'
depends 'mineos'
